---
name: lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: lint-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  cookstyle:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: debug
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0"
          bundler-cache: true
      - uses: r7kamura/rubocop-problem-matchers-action@v1  # this shows the failures in the PR
      - run: bundle exec cookstyle --chefstyle -c .rubocop.yml

  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          curl --location 'https://raw.githubusercontent.com/chef/chef_dictionary/main/chef.txt' --output chef_dictionary.txt
      - uses: streetsidesoftware/cspell-action@v9

  linelint:
    runs-on: ubuntu-latest
    name: Check if all files end in newline
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Linelint
        uses: fernandrone/linelint@0.0.6
        id: linelint
